number = "inv123456"
date = "09/08/2024"

[me]
name = "Websites R Us"
addrline1 = "1 Example Street"
addrline2 = "Exampleville 3000"
country = "Australia"
abn = "11 111 111 111"

[client]
company = "ACME Pty. Ltd."
phone = "0499 999 999"
abn = "99 999 999 999"

[[items]]
hours = 16
rate = 3.00
description = "Build website for acme.com"

[[items]]
hours = 4
rate = 2.00
description = "Testing"

[[items]]
hours = 3
rate = 2.00
description = "Deploy website"

[payment]
bsb = "123-456"
accname = "Aron Lebani"
accnumber = "123 456 789"
